export const PICKUP_POINTS = [
  "ADS Pharmacy - Nabbingo",
  "ADS Pharmacy - Kibiri",
  "ADS Pharmacy - Kyanja",
  "ADS Pharmacy - Masaka",
  "ADS Pharmacy - Mpala",
  "ADS Pharmacy - Katabi",
  "ADS Pharmacy - Namere",
  "ADS Pharmacy - Naminya, Jinja",
  "ADS Pharmacy - Bugember, Jinja",
  "ADS Pharmacy - Mbarara",
  "ADS Pharmacy - Nsasa",
  "ADS Pharmacy - Ntungamo",
  "ADS Pharmacy - Fortportal Kachwamba",
  "CP Pharma - Ntinda",
];
