export GCP_PROJECT="clinicpesa-1"
#gcloud beta artifacts docker upgrade print-iam-policy gcr.io \
#          --project=$GCP_PROJECT
export APPLICATION_NAME="cp-pharma-valentine"
export REGISTRY="gcr.io"
#export EVN="-t"
export EVN=""
export VERSION=2026021302-valentine


#nvm use 20
node -v 20

npm run build

rm -r dist/cp-pharma-valentine

mkdir -p dist/cp-pharma-valentine

cp -R dist/* dist/cp-pharma-valentine/

cp ./GKE/kubernetes/dockerfile ./dist/cp-pharma-valentine
cp ./GKE/kubernetes/nginx-custom.conf ./dist/cp-pharma-valentine
# Generate the api docker --no-cache
docker build --platform linux/amd64,linux/arm64 --no-cache=true -t $REGISTRY/$GCP_PROJECT/$APPLICATION_NAME  ./dist/cp-pharma-valentine

#docker login $REGISTRY -u $U_NAME --password-stdin $PSSWD
gcloud auth configure-docker $REGISTRY

# The version needs to be adapted to the one generated by the command above
docker tag $REGISTRY/$GCP_PROJECT/$APPLICATION_NAME us-docker.pkg.dev/$GCP_PROJECT/$REGISTRY/$APPLICATION_NAME:$VERSION


docker push us-docker.pkg.dev/$GCP_PROJECT/$REGISTRY/$APPLICATION_NAME:$VERSION


#Environmental Variables 20211219001_PROD
#./GKE/kubernetes/redis.sh > ./GKE/kubernetes/keys.txt
#./GKE/kubernetes/secret.sh

git commit -am "TAG:$VERSION"


# echo "kubectl -n cp-gt$EVN set image  deployment/cp-pharma-valentine  cp-pharma-valentine=us-docker.pkg.dev/$GCP_PROJECT/$REGISTRY/$APPLICATION_NAME:$VERSION"
# echo "kubectl -n cp-gt$EVN rollout status deployment/cp-pharma-valentine"

kubectl -n cp-gt$EVN set image deployment/cp-pharma-valentine cp-pharma-valentine=us-docker.pkg.dev/$GCP_PROJECT/$REGISTRY/$APPLICATION_NAME:$VERSION
kubectl -n cp-gt$EVN rollout status deployment/cp-pharma-valentine


#kubectl create secret docker-registry gcr-json-key \
#  --docker-server=us-docker.pkg.dev \
#  --docker-username=oauth2accesstoken \
#  --docker-password="$(gcloud auth print-access-token)" \
#  --docker-email=your-email@example.com \
#  --namespace=cp-gt

#spec:
#  imagePullSecrets:
#    - name: gcr-json-key
