FROM nginx:1.19

COPY ./ /usr/share/nginx/html/

USER root
# RUN ["ls", "/usr/share/nginx/html/images"]
# RUN ["ls", "/usr/share/nginx/html"]
#Copy default nginx configuration
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
